/*
	GCC214 - Banco de Dados - 2017/2
	Loja De Apps
	
	@author Rafael Takehara
	@author Tarik Esmin
	@author	William Abreu
	
	MySQL script que preenche todas as tabelas
    do banco de dados com valores válidos
    gerados.
*/


use LojaDeApps;


call insertUsuario('alexandre', 'alexandre@ufla.br', 'senha-alexandre', 'Alexandre Frota', 'familiar', 448.07, '2002-02-10');
call insertUsuario('joaquim', 'joaquim@ufla.br', 'senha-joaquim', 'Joaquim Grandíssimo', 'familiar', 341.4, '1976-10-25');
call insertUsuario('ricardo', 'ricardo@ufla.br', 'senha-ricardo', 'Ricardo Planeta', 'individual', 403.8, '2012-07-19');
call insertUsuario('zambaldina', 'zambaldina@ufla.br', 'senha-zambaldina', 'Zambaldina Júdice', 'familiar', 175.37, '1967-05-07');
call insertUsuario('gerson', 'gerson@ufla.br', 'senha-gerson', 'Gerson Hernandes', 'familiar', 160.74, '1993-08-13');
call insertUsuario('cristiano', 'cristiano@ufla.br', 'senha-cristiano', 'Cristiano Ribas', 'individual', 40.43, '1988-07-23');
call insertUsuario('fabiola', 'fabiola@ufla.br', 'senha-fabiola', 'Fabiola Harém', 'individual', 436.06, '1966-07-03');
call insertUsuario('virginia', 'virginia@ufla.br', 'senha-virginia', 'Virginia Póvoas', 'familiar', 349.57, '1980-02-09');
call insertUsuario('valerio', 'valerio@ufla.br', 'senha-valerio', 'Valerio Colares', 'individual', 471.89, '1960-03-05');
call insertUsuario('damiao', 'damiao@ufla.br', 'senha-damiao', 'Damiao Frade', 'estudante', 226.26, '1976-01-11');
call insertUsuario('olavo', 'olavo@ufla.br', 'senha-olavo', 'Olavo Docarvalho', 'estudante', 364.79, '1976-04-22');
call insertUsuario('agata', 'agata@ufla.br', 'senha-agata', 'Agata Ribas', 'estudante', 186.63, '2004-01-09');
call insertUsuario('solano', 'solano@ufla.br', 'senha-solano', 'Solano Amado', 'familiar', 102.0, '2003-02-19');
call insertUsuario('henriqueta', 'henriqueta@ufla.br', 'senha-henriqueta', 'Henriqueta Ribeiro', 'familiar', 416.8, '1982-01-12');
call insertUsuario('catarino', 'catarino@ufla.br', 'senha-catarino', 'Catarino Coelho', 'estudante', 50.24, '1972-02-15');
call insertUsuario('arminda', 'arminda@ufla.br', 'senha-arminda', 'Arminda Simão', 'familiar', 317.85, '2006-04-17');
call insertUsuario('nicolau', 'nicolau@ufla.br', 'senha-nicolau', 'Nicolau Barroso', 'individual', 403.77, '1986-05-22');
call insertUsuario('debora', 'debora@ufla.br', 'senha-debora', 'Debora Ferro', 'individual', 469.21, '2007-05-14');
call insertUsuario('amanda', 'amanda@ufla.br', 'senha-amanda', 'Amanda Nuds', 'individual', 389.19, '1982-08-20');
call insertUsuario('aleixo', 'aleixo@ufla.br', 'senha-aleixo', 'Aleixo Velasques', 'familiar', 77.23, '1963-03-26');


call insertEmpresa('pcenter', '90.275.5158-99', 'senha-pcenter', 'Pcenter Informática', 'Avenida dos Trabalhadores', 428, 'Zona Sul', 'Curitiba', 'França', NULL);
call insertEmpresa('contron', '58.146.7117-94', 'senha-contron', 'Contron', 'Rodovia dos Metalúrgicos', 1243, 'Centro', 'São Paulo', 'França', 'contron.com.br');
call insertEmpresa('datacel', '78.739.5239-95', 'senha-datacel', 'Datacel', 'Avenida dos Trabalhadores', 362, 'Centro', 'Perdões', 'França', NULL);
call insertEmpresa('extra', '90.409.4770-36', 'senha-extra', 'Extra Bits', 'Rua Alberto Pasqualine', 390, 'Centro', 'Perdões', 'Austrália', 'extra.com.br');
call insertEmpresa('magasyn', '10.867.6896-45', 'senha-magasyn', 'Magasyn', 'Estrada da Companhia', 331, NULL, 'Perdões', 'Brasil', 'magasyn.com.br');
call insertEmpresa('tuttistore', '53.998.2428-38', 'senha-tuttistore', 'Tuttistore', 'Rua General Oswaldo Pinto da Veiga', 473, 'Zona Norte', 'Campo Belo', 'Austrália', NULL);
call insertEmpresa('francomp', '95.306.3237-31', 'senha-francomp', 'Francomp', 'Rua Alberto Pasqualine', 1668, 'Zona Norte', 'São Paulo', 'França', NULL);
call insertEmpresa('center', '11.526.1597-34', 'senha-center', 'Center Tech', 'Rua Lúcio Bittencourt', 1030, 'Zona Sul', 'Varginha', 'França', 'center.com.br');
call insertEmpresa('compushop', '99.345.7850-71', 'senha-compushop', 'CompuShop', 'Rua Capitão Benedito Lopes Bragança', 1436, 'Zona Norte', 'Lavras', 'Brasil', 'compushop.com.br');
call insertEmpresa('infotech', '99.252.2551-65', 'senha-infotech', 'InfoTech', 'Avenida Sete de Setembro', 203, 'Zona Leste', 'Campo Belo', 'França', 'infotech.com.br');
call insertEmpresa('google', '93.506.6800-11', 'senha-google', 'Google', 'Avenida Getúlio Vargas', NULL, 'Zona Sul', 'Lavras', 'Brasil', 'google.com.br');
call insertEmpresa('microsoft', '59.567.3569-32', 'senha-microsoft', 'Microsoft', 'Avenida Lucas Evangelista', NULL, 'Zona Sul', 'Lavras', 'Brasil', 'microsoft.com.br');
call insertEmpresa('apple', '64.147.7831-47', 'senha-apple', 'Apple Inc.', 'Avenida Sete de Setembro', 21, 'Zona Sul', 'São Paulo', 'França', 'apple.com.br');
call insertEmpresa('compjunior', '70.590.5759-48', 'senha-compjunior', 'Compjunior', 'Rodovia dos Metalúrgicos', 835, 'Zona Sul', 'Curitiba', 'França', 'compjunior.com.br');
call insertEmpresa('emakers', '84.924.7733-62', 'senha-emakers', 'EMakers', 'Estrada Francisco Vilela Arantes', NULL, 'Zona Norte', 'Perdões', 'França', 'emakers.com.br');


call insertTelefone('+55 35 3634-5778', 'apple');
call insertTelefone('+55 35 4444-9208', 'apple');
call insertTelefone('+55 35 9074-6073', 'apple');
call insertTelefone('+55 35 3451-1290', 'center');
call insertTelefone('+55 35 3543-1136', 'compjunior');
call insertTelefone('+55 35 4531-1397', 'compjunior');
call insertTelefone('+55 35 3795-3827', 'compushop');
call insertTelefone('+55 35 9159-1184', 'compushop');
call insertTelefone('+55 35 3005-7891', 'contron');
call insertTelefone('+55 35 4316-0157', 'contron');
call insertTelefone('+55 35 3357-6582', 'datacel');
call insertTelefone('+55 35 3963-3761', 'emakers');
call insertTelefone('+55 35 4423-4068', 'emakers');
call insertTelefone('+55 35 9642-0432', 'emakers');
call insertTelefone('+55 35 3587-6339', 'extra');
call insertTelefone('+55 35 3449-7706', 'francomp');
call insertTelefone('+55 35 4899-3092', 'francomp');
call insertTelefone('+55 35 3084-6683', 'google');
call insertTelefone('+55 35 9425-0082', 'google');
call insertTelefone('+55 35 3091-4322', 'infotech');
call insertTelefone('+55 35 4773-3362', 'infotech');
call insertTelefone('+55 35 3568-2145', 'magasyn');
call insertTelefone('+55 35 3124-4376', 'microsoft');
call insertTelefone('+55 35 4093-0122', 'microsoft');
call insertTelefone('+55 35 9645-4334', 'microsoft');
call insertTelefone('+55 35 3111-1236', 'pcenter');
call insertTelefone('+55 35 3306-8287', 'tuttistore');
call insertTelefone('+55 35 4639-7413', 'tuttistore');


call insertEmail('suporte@apple.com', 'apple');
call insertEmail('apple@apple.com', 'apple');
call insertEmail('sac@apple.com', 'apple');
call insertEmail('suporte@center.com', 'center');
call insertEmail('center@center.com', 'center');
call insertEmail('suporte@compjunior.com', 'compjunior');
call insertEmail('compjunior@compjunior.com', 'compjunior');
call insertEmail('suporte@compushop.com', 'compushop');
call insertEmail('compushop@compushop.com', 'compushop');
call insertEmail('suporte@contron.com', 'contron');
call insertEmail('contron@contron.com', 'contron');
call insertEmail('sac@contron.com', 'contron');
call insertEmail('suporte@datacel.com', 'datacel');
call insertEmail('datacel@datacel.com', 'datacel');
call insertEmail('suporte@emakers.com', 'emakers');
call insertEmail('emakers@emakers.com', 'emakers');
call insertEmail('suporte@extra.com', 'extra');
call insertEmail('extra@extra.com', 'extra');
call insertEmail('suporte@francomp.com', 'francomp');
call insertEmail('francomp@francomp.com', 'francomp');
call insertEmail('sac@francomp.com', 'francomp');
call insertEmail('suporte@google.com', 'google');
call insertEmail('google@google.com', 'google');
call insertEmail('suporte@infotech.com', 'infotech');
call insertEmail('infotech@infotech.com', 'infotech');
call insertEmail('suporte@magasyn.com', 'magasyn');
call insertEmail('magasyn@magasyn.com', 'magasyn');
call insertEmail('suporte@microsoft.com', 'microsoft');
call insertEmail('microsoft@microsoft.com', 'microsoft');
call insertEmail('sac@microsoft.com', 'microsoft');
call insertEmail('suporte@pcenter.com', 'pcenter');
call insertEmail('pcenter@pcenter.com', 'pcenter');
call insertEmail('suporte@tuttistore.com', 'tuttistore');
call insertEmail('tuttistore@tuttistore.com', 'tuttistore');


call insertDispositivo('galaxy-pocket-1', 'cristiano', 'os x', 'galaxy', '2018.1.70', False, True, False, True);
call insertDispositivo('galaxy-pocket-1', 'aleixo', 'os x', 'galaxy', '2018.1.94', True, False, False, True);
call insertDispositivo('moto-g5-151359', 'catarino', 'os x', 'moto', '2018.1.64', True, True, True, True);
call insertDispositivo('moto-e4-151359', 'debora', 'windows', 'moto', '2018.1.60', True, False, False, True);
call insertDispositivo('moto-g5-151359', 'olavo', 'android', 'moto', '2018.1.26', True, False, True, True);
call insertDispositivo('galaxy-pocket-1', 'valerio', 'android', 'galaxy', '2018.1.85', True, True, True, True);
call insertDispositivo('galaxy-pocket-1', 'solano', 'windows', 'galaxy', '2018.1.33', True, True, True, False);
call insertDispositivo('galaxy-s7-15135', 'nicolau', 'windows', 'galaxy', '2018.1.119', True, True, True, True);
call insertDispositivo('moto-e4-151359', 'fabiola', 'android', 'moto', '2018.1.22', True, False, True, True);
call insertDispositivo('moto-g5-151359', 'amanda', 'windows', 'moto', '2018.1.38', True, False, False, False);
call insertDispositivo('galaxy-s7-15135', 'ricardo', 'android', 'galaxy', '2018.1.23', True, True, True, False);
call insertDispositivo('moto-g5-151359', 'arminda', 'ios', 'moto', '2018.1.81', False, False, False, True);
call insertDispositivo('moto-g5-151359', 'nicolau', 'windows', 'moto', '2018.1.84', True, True, False, True);


call insertAplicativo('compjunior', 'Facebook', 3803337, 'redeSocial', 'v28.80', 12);
call insertAplicativo('francomp', 'WhatsApp', 32237630, 'mensagem', 'v5.126', 10);
call insertAplicativo('compushop', 'Tinder', 46584681, 'namoro', 'v39.37', 18);
call insertAplicativo('extra', 'Internet Explorer', 52251084, 'internet', 'v24.64', NULL);
call insertAplicativo('pcenter', 'Safari', 27349884, 'internet', 'v45.148', NULL);
call insertAplicativo('tuttistore', 'Docs Explorer', 23053014, 'arquivos', 'v41.52', NULL);
call insertAplicativo('microsoft', 'Design Circuit', 10814633, 'ciencia', 'v26.87', NULL);
call insertAplicativo('pcenter', 'Discord', 15913705, 'mensagem', 'v22.54', 14);
call insertAplicativo('pcenter', 'SIG estudante', 37779915, 'educa', 'v17.51', NULL);
call insertAplicativo('magasyn', 'Governo Federal APP', 79304927, 'politica', 'v46.151', NULL);
call insertAplicativo('extra', 'Socratic', 44123067, 'educação', 'v37.127', 16);
call insertAplicativo('emakers', 'Airbnb', 27014198, 'vendas', 'v26.88', 18);
call insertAplicativo('compjunior', 'CastBox', 57618221, NULL, 'v48.13', 12);
call insertAplicativo('magasyn', 'Medite.se', 43010255, 'conforto', 'v11.23', NULL);
call insertAplicativo('google', 'Sons Relaxantes', 66353524, 'conforto', 'v24.53', NULL);
call insertAplicativo('compjunior', 'Melhores crianças', 49712318, NULL, 'v36.106', NULL);
call insertAplicativo('tuttistore', 'Star Walk 2', 56570488, 'jogo', 'v25.58', 10);
call insertAplicativo('emakers', 'Mondly', 38389366, NULL, 'v18.123', NULL);
call insertAplicativo('francomp', 'Cidade Sago Mini', 32290538, 'jogo', 'v43.140', 10);
call insertAplicativo('francomp', 'A Vida na Toca', 62348433, 'educação', 'v2.85', NULL);
call insertAplicativo('francomp', 'Dr. Panda Café', 40577385, 'educação', 'v35.46', NULL);
call insertAplicativo('contron', 'Messenger Lite', 10708990, 'mensagens', 'v45.125', 12);
call insertAplicativo('center', 'Photo Editor', 9373181, 'imagem', 'v17.35', NULL);
call insertAplicativo('contron', 'Kwai', 48867601, NULL, 'v42.4', 14);
call insertAplicativo('francomp', 'MagiMobile', 35437909, 'imagem', 'v15.63', NULL);
call insertAplicativo('infotech', 'Selfie Camera', 22634387, 'imagem', 'v38.14', 12);
call insertAplicativo('microsoft', 'Notebook', 73515798, 'texto', 'v42.150', NULL);
call insertAplicativo('francomp', 'Journey', 51876310, 'notícia', 'v30.48', 12);
call insertAplicativo('tuttistore', 'Today Weather', 64542400, 'notícia', 'v38.47', 10);


call insertIdioma('en-US', 'Facebook', 'compjunior');
call insertIdioma('pt-BR', 'Facebook', 'compjunior');
call insertIdioma('en-US', 'WhatsApp', 'francomp');
call insertIdioma('en-US', 'Tinder', 'compushop');
call insertIdioma('en-US', 'Internet Explorer', 'extra');
call insertIdioma('pt-BR', 'Internet Explorer', 'extra');
call insertIdioma('en-US', 'Safari', 'pcenter');
call insertIdioma('en-US', 'Docs Explorer', 'tuttistore');
call insertIdioma('en-US', 'Design Circuit', 'microsoft');
call insertIdioma('pt-BR', 'Design Circuit', 'microsoft');
call insertIdioma('en-US', 'Discord', 'pcenter');
call insertIdioma('en-US', 'SIG estudante', 'pcenter');
call insertIdioma('en-US', 'Governo Federal APP', 'magasyn');
call insertIdioma('pt-BR', 'Governo Federal APP', 'magasyn');
call insertIdioma('en-US', 'Socratic', 'extra');
call insertIdioma('en-US', 'Airbnb', 'emakers');
call insertIdioma('en-US', 'CastBox', 'compjunior');
call insertIdioma('pt-BR', 'CastBox', 'compjunior');
call insertIdioma('en-US', 'Medite.se', 'magasyn');
call insertIdioma('en-US', 'Sons Relaxantes', 'google');
call insertIdioma('en-US', 'Melhores crianças', 'compjunior');
call insertIdioma('pt-BR', 'Melhores crianças', 'compjunior');
call insertIdioma('en-US', 'Star Walk 2', 'tuttistore');
call insertIdioma('en-US', 'Mondly', 'emakers');
call insertIdioma('en-US', 'Cidade Sago Mini', 'francomp');
call insertIdioma('pt-BR', 'Cidade Sago Mini', 'francomp');
call insertIdioma('en-US', 'A Vida na Toca', 'francomp');
call insertIdioma('en-US', 'Dr. Panda Café', 'francomp');
call insertIdioma('en-US', 'Messenger Lite', 'contron');
call insertIdioma('pt-BR', 'Messenger Lite', 'contron');
call insertIdioma('en-US', 'Photo Editor', 'center');
call insertIdioma('en-US', 'Kwai', 'contron');
call insertIdioma('en-US', 'MagiMobile', 'francomp');
call insertIdioma('pt-BR', 'MagiMobile', 'francomp');
call insertIdioma('en-US', 'Selfie Camera', 'infotech');
call insertIdioma('en-US', 'Notebook', 'microsoft');
call insertIdioma('en-US', 'Journey', 'francomp');
call insertIdioma('pt-BR', 'Journey', 'francomp');
call insertIdioma('en-US', 'Today Weather', 'tuttistore');


call insertSistema('ios', 'Facebook', 'compjunior');
call insertSistema('windows', 'Facebook', 'compjunior');
call insertSistema('linux', 'Facebook', 'compjunior');
call insertSistema('ios', 'WhatsApp', 'francomp');
call insertSistema('windows', 'WhatsApp', 'francomp');
call insertSistema('linux', 'WhatsApp', 'francomp');
call insertSistema('android', 'Tinder', 'compushop');
call insertSistema('ios', 'Tinder', 'compushop');
call insertSistema('windows', 'Tinder', 'compushop');
call insertSistema('ios', 'Internet Explorer', 'extra');
call insertSistema('windows', 'Internet Explorer', 'extra');
call insertSistema('linux', 'Internet Explorer', 'extra');
call insertSistema('windows', 'Safari', 'pcenter');
call insertSistema('linux', 'Safari', 'pcenter');
call insertSistema('os x', 'Safari', 'pcenter');
call insertSistema('ios', 'Docs Explorer', 'tuttistore');
call insertSistema('windows', 'Docs Explorer', 'tuttistore');
call insertSistema('linux', 'Docs Explorer', 'tuttistore');
call insertSistema('os x', 'Design Circuit', 'microsoft');
call insertSistema('android', 'Design Circuit', 'microsoft');
call insertSistema('ios', 'Design Circuit', 'microsoft');
call insertSistema('windows', 'Discord', 'pcenter');
call insertSistema('linux', 'Discord', 'pcenter');
call insertSistema('os x', 'Discord', 'pcenter');
call insertSistema('ios', 'SIG estudante', 'pcenter');
call insertSistema('windows', 'SIG estudante', 'pcenter');
call insertSistema('linux', 'SIG estudante', 'pcenter');
call insertSistema('os x', 'Governo Federal APP', 'magasyn');
call insertSistema('android', 'Governo Federal APP', 'magasyn');
call insertSistema('ios', 'Governo Federal APP', 'magasyn');
call insertSistema('ios', 'Socratic', 'extra');
call insertSistema('windows', 'Socratic', 'extra');
call insertSistema('linux', 'Socratic', 'extra');
call insertSistema('os x', 'Airbnb', 'emakers');
call insertSistema('android', 'Airbnb', 'emakers');
call insertSistema('ios', 'Airbnb', 'emakers');
call insertSistema('android', 'CastBox', 'compjunior');
call insertSistema('ios', 'CastBox', 'compjunior');
call insertSistema('windows', 'CastBox', 'compjunior');
call insertSistema('linux', 'Medite.se', 'magasyn');
call insertSistema('os x', 'Medite.se', 'magasyn');
call insertSistema('android', 'Medite.se', 'magasyn');
call insertSistema('ios', 'Sons Relaxantes', 'google');
call insertSistema('windows', 'Sons Relaxantes', 'google');
call insertSistema('linux', 'Sons Relaxantes', 'google');
call insertSistema('windows', 'Melhores crianças', 'compjunior');
call insertSistema('linux', 'Melhores crianças', 'compjunior');
call insertSistema('os x', 'Melhores crianças', 'compjunior');
call insertSistema('android', 'Star Walk 2', 'tuttistore');
call insertSistema('ios', 'Star Walk 2', 'tuttistore');
call insertSistema('windows', 'Star Walk 2', 'tuttistore');
call insertSistema('linux', 'Mondly', 'emakers');
call insertSistema('os x', 'Mondly', 'emakers');
call insertSistema('android', 'Mondly', 'emakers');
call insertSistema('windows', 'Cidade Sago Mini', 'francomp');
call insertSistema('linux', 'Cidade Sago Mini', 'francomp');
call insertSistema('os x', 'Cidade Sago Mini', 'francomp');
call insertSistema('android', 'A Vida na Toca', 'francomp');
call insertSistema('ios', 'A Vida na Toca', 'francomp');
call insertSistema('windows', 'A Vida na Toca', 'francomp');
call insertSistema('windows', 'Dr. Panda Café', 'francomp');
call insertSistema('linux', 'Dr. Panda Café', 'francomp');
call insertSistema('os x', 'Dr. Panda Café', 'francomp');
call insertSistema('ios', 'Messenger Lite', 'contron');
call insertSistema('windows', 'Messenger Lite', 'contron');
call insertSistema('linux', 'Messenger Lite', 'contron');
call insertSistema('ios', 'Photo Editor', 'center');
call insertSistema('windows', 'Photo Editor', 'center');
call insertSistema('linux', 'Photo Editor', 'center');
call insertSistema('linux', 'Kwai', 'contron');
call insertSistema('os x', 'Kwai', 'contron');
call insertSistema('android', 'Kwai', 'contron');
call insertSistema('android', 'MagiMobile', 'francomp');
call insertSistema('ios', 'MagiMobile', 'francomp');
call insertSistema('windows', 'MagiMobile', 'francomp');
call insertSistema('os x', 'Selfie Camera', 'infotech');
call insertSistema('android', 'Selfie Camera', 'infotech');
call insertSistema('ios', 'Selfie Camera', 'infotech');
call insertSistema('linux', 'Notebook', 'microsoft');
call insertSistema('os x', 'Notebook', 'microsoft');
call insertSistema('android', 'Notebook', 'microsoft');
call insertSistema('ios', 'Journey', 'francomp');
call insertSistema('windows', 'Journey', 'francomp');
call insertSistema('linux', 'Journey', 'francomp');
call insertSistema('android', 'Today Weather', 'tuttistore');
call insertSistema('ios', 'Today Weather', 'tuttistore');
call insertSistema('windows', 'Today Weather', 'tuttistore');


call insertAdquireLicenca('agata', 'Messenger Lite', 'contron', 'opensource', NULL, NULL);
call insertAdquireLicenca('agata', 'MagiMobile', 'francomp', 'comercial', 92.99, 'boleto');
call insertAdquireLicenca('agata', 'Journey', 'francomp', 'comercial', 35.99, 'debito');
call insertAdquireLicenca('agata', 'Design Circuit', 'microsoft', 'opensource', NULL, NULL);
call insertAdquireLicenca('agata', 'Socratic', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('aleixo', 'Sons Relaxantes', 'google', 'freeware', NULL, NULL);
call insertAdquireLicenca('aleixo', 'MagiMobile', 'francomp', 'comercial', 60.99, 'debito');
call insertAdquireLicenca('aleixo', 'Design Circuit', 'microsoft', 'freeware', NULL, NULL);
call insertAdquireLicenca('aleixo', 'Notebook', 'microsoft', 'opensource', NULL, NULL);
call insertAdquireLicenca('aleixo', 'Journey', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('alexandre', 'Governo Federal APP', 'magasyn', 'opensource', NULL, NULL);
call insertAdquireLicenca('alexandre', 'Socratic', 'extra', 'freeware', NULL, NULL);
call insertAdquireLicenca('alexandre', 'Medite.se', 'magasyn', 'comercial', 194.99, 'paypal');
call insertAdquireLicenca('alexandre', 'Dr. Panda Café', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('alexandre', 'CastBox', 'compjunior', 'comercial', 172.99, 'debito');
call insertAdquireLicenca('amanda', 'Cidade Sago Mini', 'francomp', 'comercial', 98.99, 'debito');
call insertAdquireLicenca('amanda', 'Kwai', 'contron', 'freeware', NULL, NULL);
call insertAdquireLicenca('amanda', 'Mondly', 'emakers', 'freeware', NULL, NULL);
call insertAdquireLicenca('amanda', 'Melhores crianças', 'compjunior', 'comercial', 58.99, 'paypal');
call insertAdquireLicenca('amanda', 'Dr. Panda Café', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('arminda', 'Internet Explorer', 'extra', 'comercial', 82.99, 'paypal');
call insertAdquireLicenca('arminda', 'Facebook', 'compjunior', 'comercial', 20.99, 'bitcoin');
call insertAdquireLicenca('arminda', 'Docs Explorer', 'tuttistore', 'comercial', 127.99, 'debito');
call insertAdquireLicenca('arminda', 'Messenger Lite', 'contron', 'comercial', 175.99, 'debito');
call insertAdquireLicenca('arminda', 'Star Walk 2', 'tuttistore', 'opensource', NULL, NULL);
call insertAdquireLicenca('catarino', 'Photo Editor', 'center', 'freeware', NULL, NULL);
call insertAdquireLicenca('catarino', 'Safari', 'pcenter', 'freeware', NULL, NULL);
call insertAdquireLicenca('catarino', 'Kwai', 'contron', 'freeware', NULL, NULL);
call insertAdquireLicenca('catarino', 'Discord', 'pcenter', 'opensource', NULL, NULL);
call insertAdquireLicenca('catarino', 'Governo Federal APP', 'magasyn', 'comercial', 189.99, 'bitcoin');
call insertAdquireLicenca('cristiano', 'Internet Explorer', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('cristiano', 'Docs Explorer', 'tuttistore', 'opensource', NULL, NULL);
call insertAdquireLicenca('cristiano', 'Governo Federal APP', 'magasyn', 'comercial', 29.99, 'debito');
call insertAdquireLicenca('cristiano', 'Medite.se', 'magasyn', 'freeware', NULL, NULL);
call insertAdquireLicenca('cristiano', 'Facebook', 'compjunior', 'freeware', NULL, NULL);
call insertAdquireLicenca('damiao', 'Discord', 'pcenter', 'opensource', NULL, NULL);
call insertAdquireLicenca('damiao', 'MagiMobile', 'francomp', 'comercial', 30.99, 'boleto');
call insertAdquireLicenca('damiao', 'SIG estudante', 'pcenter', 'comercial', 33.99, 'credito');
call insertAdquireLicenca('damiao', 'Today Weather', 'tuttistore', 'freeware', NULL, NULL);
call insertAdquireLicenca('damiao', 'Notebook', 'microsoft', 'comercial', 166.99, 'debito');
call insertAdquireLicenca('debora', 'CastBox', 'compjunior', 'freeware', NULL, NULL);
call insertAdquireLicenca('debora', 'Medite.se', 'magasyn', 'comercial', 108.99, 'credito');
call insertAdquireLicenca('debora', 'SIG estudante', 'pcenter', 'freeware', NULL, NULL);
call insertAdquireLicenca('debora', 'Socratic', 'extra', 'freeware', NULL, NULL);
call insertAdquireLicenca('debora', 'WhatsApp', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('fabiola', 'Photo Editor', 'center', 'opensource', NULL, NULL);
call insertAdquireLicenca('fabiola', 'Airbnb', 'emakers', 'freeware', NULL, NULL);
call insertAdquireLicenca('fabiola', 'Messenger Lite', 'contron', 'freeware', NULL, NULL);
call insertAdquireLicenca('fabiola', 'Internet Explorer', 'extra', 'freeware', NULL, NULL);
call insertAdquireLicenca('fabiola', 'WhatsApp', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('gerson', 'Mondly', 'emakers', 'opensource', NULL, NULL);
call insertAdquireLicenca('gerson', 'Melhores crianças', 'compjunior', 'opensource', NULL, NULL);
call insertAdquireLicenca('gerson', 'Design Circuit', 'microsoft', 'comercial', 174.99, 'boleto');
call insertAdquireLicenca('gerson', 'CastBox', 'compjunior', 'opensource', NULL, NULL);
call insertAdquireLicenca('gerson', 'Tinder', 'compushop', 'opensource', NULL, NULL);
call insertAdquireLicenca('henriqueta', 'Internet Explorer', 'extra', 'freeware', NULL, NULL);
call insertAdquireLicenca('henriqueta', 'WhatsApp', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('henriqueta', 'Star Walk 2', 'tuttistore', 'freeware', NULL, NULL);
call insertAdquireLicenca('henriqueta', 'Journey', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('henriqueta', 'Socratic', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('joaquim', 'A Vida na Toca', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('joaquim', 'Internet Explorer', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('joaquim', 'Selfie Camera', 'infotech', 'comercial', 193.99, 'paypal');
call insertAdquireLicenca('joaquim', 'Medite.se', 'magasyn', 'opensource', NULL, NULL);
call insertAdquireLicenca('joaquim', 'Tinder', 'compushop', 'freeware', NULL, NULL);
call insertAdquireLicenca('nicolau', 'Photo Editor', 'center', 'comercial', 100.99, 'bitcoin');
call insertAdquireLicenca('nicolau', 'Dr. Panda Café', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('nicolau', 'Journey', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('nicolau', 'Socratic', 'extra', 'comercial', 80.99, 'debito');
call insertAdquireLicenca('nicolau', 'Mondly', 'emakers', 'opensource', NULL, NULL);
call insertAdquireLicenca('olavo', 'Cidade Sago Mini', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('olavo', 'Messenger Lite', 'contron', 'opensource', NULL, NULL);
call insertAdquireLicenca('olavo', 'Facebook', 'compjunior', 'comercial', 187.99, 'bitcoin');
call insertAdquireLicenca('olavo', 'Star Walk 2', 'tuttistore', 'comercial', 144.99, 'paypal');
call insertAdquireLicenca('olavo', 'CastBox', 'compjunior', 'comercial', 26.99, 'boleto');
call insertAdquireLicenca('ricardo', 'Safari', 'pcenter', 'comercial', 165.99, 'paypal');
call insertAdquireLicenca('ricardo', 'WhatsApp', 'francomp', 'comercial', 86.99, 'credito');
call insertAdquireLicenca('ricardo', 'Socratic', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('ricardo', 'Sons Relaxantes', 'google', 'comercial', 26.99, 'paypal');
call insertAdquireLicenca('ricardo', 'Dr. Panda Café', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('solano', 'Tinder', 'compushop', 'freeware', NULL, NULL);
call insertAdquireLicenca('solano', 'CastBox', 'compjunior', 'freeware', NULL, NULL);
call insertAdquireLicenca('solano', 'Mondly', 'emakers', 'comercial', 103.99, 'boleto');
call insertAdquireLicenca('solano', 'Discord', 'pcenter', 'comercial', 52.99, 'paypal');
call insertAdquireLicenca('solano', 'Internet Explorer', 'extra', 'comercial', 91.99, 'credito');
call insertAdquireLicenca('valerio', 'WhatsApp', 'francomp', 'opensource', NULL, NULL);
call insertAdquireLicenca('valerio', 'Facebook', 'compjunior', 'comercial', 90.99, 'paypal');
call insertAdquireLicenca('valerio', 'Socratic', 'extra', 'freeware', NULL, NULL);
call insertAdquireLicenca('valerio', 'Today Weather', 'tuttistore', 'opensource', NULL, NULL);
call insertAdquireLicenca('valerio', 'Design Circuit', 'microsoft', 'opensource', NULL, NULL);
call insertAdquireLicenca('virginia', 'Socratic', 'extra', 'opensource', NULL, NULL);
call insertAdquireLicenca('virginia', 'Kwai', 'contron', 'freeware', NULL, NULL);
call insertAdquireLicenca('virginia', 'CastBox', 'compjunior', 'freeware', NULL, NULL);
call insertAdquireLicenca('virginia', 'MagiMobile', 'francomp', 'comercial', 186.99, 'credito');
call insertAdquireLicenca('virginia', 'SIG estudante', 'pcenter', 'opensource', NULL, NULL);
call insertAdquireLicenca('zambaldina', 'Safari', 'pcenter', 'opensource', NULL, NULL);
call insertAdquireLicenca('zambaldina', 'Medite.se', 'magasyn', 'comercial', 147.99, 'credito');
call insertAdquireLicenca('zambaldina', 'Mondly', 'emakers', 'opensource', NULL, NULL);
call insertAdquireLicenca('zambaldina', 'Journey', 'francomp', 'freeware', NULL, NULL);
call insertAdquireLicenca('zambaldina', 'Governo Federal APP', 'magasyn', 'opensource', NULL, NULL);



